### ISSUE TITLE
[Bug] Connected package not responding

### ISSUE THREAD

**Issue by technicalhafiz** [siavash79/PixelXpert#732]
### Describe the issue

successfully flash Magisk and LSposed Module but package not responding error comes

### Steps to reproduce

Successfully Flash Magisk and LSposed Module but package not responding error comes

i try to open these programs and try again but not responding error resolve for sometime but again same error comes
![WhatsApp Image 2023-11-06 at 5 23 08 PM](https://github.com/siavash79/PixelXpert/assets/70044448/6b39a064-ddd3-48ad-ba0e-e986ee43697a)

### Your device setup (Please take some time to give correct information here)

Pixel 4xl Android 13 stock
Magisk 26.4 Installed 
LSposed 1.9.2 (7024) - Zygisk
Pixel Expert Canary-294 (294) Install + Same Problem Comes with stable version
Android Security Update Oct-5-2022

### Logs

----part 1 start----
[ 2023-11-06T17:32:44.684     1000:  1863:  1863 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2023-11-06T17:32:44.763     1000:  1863:  1863 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2023-11-06T17:32:54.503    10271:  2661:  2661 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2023-11-06T17:32:54.579    10271:  2661:  2661 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2023-11-06T17:32:54.691    10271:  2661:  2661 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:54.691    10271:  2661:  2661 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:32:54.704     1000:  1863:  2150 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:54.705     1000:  1863:  2150 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:32:54.830    10210:  2682:  2682 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2023-11-06T17:32:54.907    10210:  2682:  2682 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2023-11-06T17:32:54.946    10210:  2682:  2682 I/LSPosed-Bridge  ] This version isn't compatible with your ROM. Exiting...
[ 2023-11-06T17:32:55.789     1000:  1863:  1863 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:55.790     1000:  1863:  1863 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:32:55.838     1000:  1863:  1863 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:55.840     1000:  1863:  1863 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:32:55.906     1001:  2906:  2906 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2023-11-06T17:32:55.907     1000:  2932:  2932 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2023-11-06T17:32:55.976     1001:  2906:  2906 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2023-11-06T17:32:55.992     1000:  2932:  2932 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2023-11-06T17:32:56.032     1001:  2906:  2906 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:56.032     1001:  2906:  2906 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:32:56.079     1000:  2932:  2932 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:56.080     1000:  2932:  2932 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:32:56.179    10198:  3070:  3070 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2023-11-06T17:32:56.283    10198:  3070:  3070 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2023-11-06T17:32:56.383    10198:  3070:  3070 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:56.384    10198:  3070:  3070 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:32:58.077    10122:  3522:  3522 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2023-11-06T17:32:58.163    10122:  3522:  3522 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2023-11-06T17:32:58.322    10122:  3522:  3522 I/LSPosed-Bridge  ] PixelXpert Version: canary-294
[ 2023-11-06T17:32:58.323    10122:  3522:  3522 I/LSPosed-Bridge  ] PixelXpert Records: 18
[ 2023-11-06T17:35:50.441    10198:  3070:  3070 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to read from null array
	at sh.siava.pixelxpert.modpacks.launcher.CustomNavGestures.lambda$saveFocusedTask$0$sh-siava-pixelxpert-modpacks-launcher-CustomNavGestures(CustomNavGestures.java:256)
	at sh.siava.pixelxpert.modpacks.launcher.CustomNavGestures$$ExternalSyntheticLambda0.test(Unknown Source:2)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:186)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1619)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:134)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:531)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:517)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:503)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:484)
	at sh.siava.pixelxpert.modpacks.launcher.CustomNavGestures.saveFocusedTask(CustomNavGestures.java:258)
	at sh.siava.pixelxpert.modpacks.launcher.CustomNavGestures.onMotionEvent(CustomNavGestures.java:157)
	at sh.siava.pixelxpert.modpacks.launcher.CustomNavGestures.access$200(CustomNavGestures.java:34)
	at sh.siava.pixelxpert.modpacks.launcher.CustomNavGestures$3.beforeHookedMethod(CustomNavGestures.java:134)
	at pDnnUeGMShS.Yk.BwoG.Dl.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:179)
	at LSPHooker_.onMotionEvent(Unknown Source:11)
	at com.android.quickstep.TouchInteractionService.onInputEvent(Unknown Source:353)
	at com.android.quickstep.TouchInteractionService.b(Unknown Source:0)
	at com.android.quickstep.a3.onInputEvent(Unknown Source:2)
	at com.android.systemui.shared.system.InputChannelCompat$InputEventReceiver$1.onInputEvent(Unknown Source:2)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by siavash79** [comment]
Tell me this: how long after reboot did you take this screenshot?

Secondly: did you try enabling any of mods? What was the result?

**Comment by technicalhafiz** [comment]
> Tell me this: how long after reboot did you take this screenshot?
> 
> Secondly: did you try enabling any of mods? What was the result?

Almost 4-5 Minutes Later

**Comment by technicalhafiz** [comment]
> Please use this method to capture logs and attach them here:
> 
> ![IMG_20231106_204107_217.jpg](https://user-images.githubusercontent.com/27622683/280828802-63ec05e7-4dde-4a58-b5e5-9bdb620b66b2.jpg)



> Please use this method to capture logs and attach them here:
> 
> ![IMG_20231106_204107_217.jpg](https://user-images.githubusercontent.com/27622683/280828802-63ec05e7-4dde-4a58-b5e5-9bdb620b66b2.jpg)

[LSPosed_2023-11-06T17_35_43.671164.zip](https://github.com/siavash79/PixelXpert/files/13279166/LSPosed_2023-11-06T17_35_43.671164.zip)

**Comment by siavash79** [comment]
you should use version 2.4.1 and avoid upgrading
