### ISSUE TITLE
[Bug] App crashes on launch

### ISSUE THREAD

**Issue by KBapna** [siavash79/PixelXpert#752]
### Describe the issue

Pixel Xpert app crashes after the update from 3.1.0 to 3.2.0. The module worked perfectly on v3.1.0.

### Steps to reproduce

Install Magisk module
Check enabled in lsposed app
Launch the app
**App crashes**

### Expected behavior

App should not Crash

### Your device setup (Please take some time to give correct information here)

Redmi K30 Evolution X custom rom
Android 13
Magisk 26.4
Lsposed 1.9.2

### Logs

Logcat -v long

ASTART u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=sh.siava.pixelxpert/.SplashScreenActivityNormalIcon} from uid 10481
Start proc 21013:sh.siava.pixelxpert/u0a595 for next-top-activity {sh.siava.pixelxpert/sh.siava.pixelxpert.SplashScreenActivityNormalIcon}
[ 12-07 02:23:39.381 21013:21013 E/iava.pixelxpert ]
[ 12-07 02:23:39.389 21013:21013 W/iava.pixelxpert ]
[ 12-07 02:23:39.389 21013:21013 W/iava.pixelxpert ]
[ 12-07 02:23:39.389 21013:21013 W/iava.pixelxpert ]
[ 12-07 02:23:39.405 21013:21013 W/iava.pixelxpert ]
[ 12-07 02:23:39.405 21013:21013 W/iava.pixelxpert ]
[ 12-07 02:23:39.405 21013:21013 W/iava.pixelxpert ]
[ 12-07 02:23:39.406 21013:21013 W/iava.pixelxpert ]
Loading xposed for sh.siava.pixelxpert/10595
Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 12-07 02:23:39.555 21013:21013 W/iava.pixelxpert ]
  Loading class sh.siava.pixelxpert.XPEntry
[ 12-07 02:23:39.634 21013:21013 E/iava.pixelxpert ]
[ 12-07 02:23:39.765 21013:21013 W/iava.pixelxpert ]
ANGLE Developer option for 'sh.siava.pixelxpert' set to: 'default'
ANGLE GameManagerService for sh.siava.pixelxpert: false
Loading provider sh.siava.pixelxpert: sh.siava.pixelxpert.utils.RemotePrefProvider
Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{sh.siava.pixelxpert/sh.siava.pixelxpert.ui.activities.SplashScreenActivity}: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
Caused by: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
Caused by: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
        at sh.siava.pixelxpert.databinding.ActivitySplashScreenBinding.inflate(ActivitySplashScreenBinding.java:60)
        at sh.siava.pixelxpert.databinding.ActivitySplashScreenBinding.inflate(ActivitySplashScreenBinding.java:54)
        at sh.siava.pixelxpert.ui.activities.SplashScreenActivity.onCreate(SplashScreenActivity.java:46)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 16: TypedValue{t=0x2/d=0x7f04011d a=-1}, theme={InheritanceMap=[id=0x7f14000ash.siava.pixelxpert:style/Animation.MaterialComponents.BottomSheetDialog, id=0x7f140002sh.siava.pixelxpert:style/Animation.AppCompat.Dialog, id=0x7f14000fsh.siava.pixelxpert:style/Base.Animation.AppCompat.Dialog, id=0x1030000android:style/Animation], Themes=[sh.siava.pixelxpert:style/Animation.MaterialComponents.BottomSheetDialog, forced, sh.siava.pixelxpert:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
Process: sh.siava.pixelxpert, PID: 21013
java.lang.RuntimeException: Unable to start activity ComponentInfo{sh.siava.pixelxpert/sh.siava.pixelxpert.ui.activities.SplashScreenActivity}: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
Caused by: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
Caused by: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
        at sh.siava.pixelxpert.databinding.ActivitySplashScreenBinding.inflate(ActivitySplashScreenBinding.java:60)
        at sh.siava.pixelxpert.databinding.ActivitySplashScreenBinding.inflate(ActivitySplashScreenBinding.java:54)
        at sh.siava.pixelxpert.ui.activities.SplashScreenActivity.onCreate(SplashScreenActivity.java:46)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 16: TypedValue{t=0x2/d=0x7f04011d a=-1}, theme={InheritanceMap=[id=0x7f14000ash.siava.pixelxpert:style/Animation.MaterialComponents.BottomSheetDialog, id=0x7f140002sh.siava.pixelxpert:style/Animation.AppCompat.Dialog, id=0x7f14000fsh.siava.pixelxpert:style/Base.Animation.AppCompat.Dialog, id=0x1030000android:style/Animation], Themes=[sh.siava.pixelxpert:style/Animation.MaterialComponents.BottomSheetDialog, forced, sh.siava.pixelxpert:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}                                   Force finishing activity sh.siava.pixelxpert/.SplashScreenActivityNormalIcon                                                      Showing crash dialog for package sh.siava.pixelxpert u0
Window{c07a036 u0 Application Error: sh.siava.pixelxpert}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@f30609, mPriority=0}
Channel [Gesture Monitor] swipe-up (server) is stealing touch from [c07a036 Application Error: sh.siava.pixelxpert (server), [Gesture Monitor] edge-swipe (server), [Gesture Monitor] onehanded-touch (server)]
Window{c07a036 u0 Application Error: sh.siava.pixelxpert}: Setting back callback null
  Force finishing activity sh.siava.pixelxpert/.SplashScreenActivityNormalIcon
Killing 21013:sh.siava.pixelxpert/u0a595 (adj 0): crash
Input channel object '2154c16 Splash Screen sh.siava.pixelxpert (client)' was disposed without first being removed with the input manager!
Got obituary of 21013:sh.siava.pixelxpert                         Input channel object 'c07a036 Application Error: sh.siava.pixelxpert (client)' was disposed without first being removed with the input manager!
Activity top resumed state loss timeout for ActivityRecord{a52254a u0 sh.siava.pixelxpert/.SplashScreenActivityNormalIcon} t-1 f}}

**Comment by KBapna** [comment]
I know, my phone is not officially supported but, since old version worked, I thought this will too.
Thanks

**Comment by mld9401** [comment]
Same here

POCO X3 NFC 
PixelOS 13
Magisk 26.4

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
