### ISSUE TITLE
The latest version would crash when first launch after upgraded.

### ISSUE THREAD

**Issue by StarVase** [siavash79/PixelXpert#797]
Here are the crash log

FATAL EXCEPTION: main
Process: sh.siava.pixelxpert, PID: 17834
java.lang.RuntimeException: Unable to start activity ComponentInfo{sh.siava.pixelxpert/sh.siava.pixelxpert.ui.activities.SplashScreenActivity}: android.view.InflateException: Binary XML file line #26 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #26 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.textview.MaterialTextView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.view.InflateException: Binary XML file line #26 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #26 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.textview.MaterialTextView
Caused by: android.view.InflateException: Binary XML file line #26 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.textview.MaterialTextView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at java.lang.reflect.Method.invoke(Native Method)
	at rhgBjq.j.vXfmkQzYca.NF.mc.cRX.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at sh.siava.pixelxpert.databinding.ActivitySplashScreenBinding.inflate(ActivitySplashScreenBinding.java:59)
	at sh.siava.pixelxpert.databinding.ActivitySplashScreenBinding.inflate(ActivitySplashScreenBinding.java:53)
	at sh.siava.pixelxpert.ui.activities.SplashScreenActivity.onCreate(SplashScreenActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:8348)
	at android.app.Activity.performCreate(Activity.java:8327)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040115 a=-1}, theme={InheritanceMap=[id=0x7f14000ash.siava.pixelxpert:style/Animation.MaterialComponents.BottomSheetDialog, id=0x7f140002sh.siava.pixelxpert:style/Animation.AppCompat.Dialog, id=0x7f14000fsh.siava.pixelxpert:style/Base.Animation.AppCompat.Dialog, id=0x1030000android:style/Animation], Themes=[sh.siava.pixelxpert:style/Animation.MaterialComponents.BottomSheetDialog, forced, sh.siava.pixelxpert:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:600)
	at XY.p.uTX.RuFpOJjbTelfSj.ources$XTypedArray.getColorStateList(Unknown Source:84)
	at android.widget.TextView.readTextAppearance(TextView.java:4123)
	at android.widget.TextView.<init>(TextView.java:1165)
	at android.widget.TextView.<init>(TextView.java:1066)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:113)
	at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:92)
	at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:87)
	... 32 more

**Comment by EleoXDA** [comment]
This bugreport is useless. Read bugreport template and fill ALL information + CORRECT LOGS
