### ISSUE TITLE
PixelXpert not queryable by hooked packages

### ISSUE THREAD

**Issue by TebbeUbben** [siavash79/PixelXpert#798]
On my phone (Pixel 6 Pro / Android 14 / Feb. Update), PixelXpert only partially works by default after installing. In the "Hooks" section of the app, I can see that only the Android system package is responsive. All other packages show "Package not responding". In the LSPosed logs, they throw the following exception:

```
android.content.pm.PackageManager$NameNotFoundException: Application package sh.siava.pixelxpert not found
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2695)
	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2660)
	at sh.siava.pixelxpert.modpacks.XPLauncher$2.afterHookedMethod(XPLauncher.java:109)
	at Bte.ZPhMKikfZ.IChuUTVO.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.newApplication(Unknown Source:17)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7018)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

This is due to Android filtering visible packages for privacy reasons. Apparently, these restrictions also apply to certain system packages. After running `adb shell pm install -r --force-queryable /system/priv-app/PixelXpert/PixelXpert.apk` the app starts working, but ideally it should also work without reinstalling it as a user package.

**Comment by siavash79** [comment]
I need to send you a file for testing. Can you message me on telegram?

**Comment by antoinepod** [comment]
> I need to send you a file for testing. Can you message me on telegram?

Is this supposed to be fixed ? I still have the issue even with the last canary updates
