### ISSUE TITLE
[Bug] Module not loading because of NoSuchMethodError

### ISSUE THREAD

**Issue by Guarmanda** [siavash79/PixelXpert#820]
### Describe the issue

NoSuchMethodError when loading on lsposed

### Steps to reproduce

1. Download version 3.3.2, and install it with magisk and lsposed on lineageos
2. Blow up in tears because of lsposed logs

Fun fact: I hadn't any problem with old legacy version, but I updated lsposed at same time, so I don't really know where the problem comes from

### Expected behavior

App loads

### Your device setup (Please take some time to give correct information here)

- xiaomi mi 11i (haydn)
- android 13 (lineageos)
- magisk 26.1
- zygisk  - lsposed 1.9.2
- pixel xpert v3.3.2

### Logs

[ 2024-04-03T18:35:35.036    10151:  2750:  2750 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.settingslib.fuelgauge.BatteryStatus#getChargingSpeed(android.app.ContextImpl)
	at Uo.XbIH.jSqZxki.VImFHB.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at Uo.XbIH.jSqZxki.VImFHB.XposedHelpers.f(Unknown Source:0)
	at Uo.XbIH.jSqZxki.VImFHB.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at Uo.XbIH.jSqZxki.VImFHB.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at Uo.XbIH.jSqZxki.VImFHB.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at Uo.XbIH.jSqZxki.VImFHB.XposedHelpers.callMethod(SourceFile:2)
	at sh.siava.pixelxpert.modpacks.systemui.BatteryDataProvider$2.afterHookedMethod(BatteryDataProvider.java:78)
	at Uo.XbIH.jSqZxki.VImFHB.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.constructor(Unknown Source:8)
	at com.android.keyguard.KeyguardUpdateMonitor.<init>(KeyguardUpdateMonitor.java:88)
	at com.android.keyguard.KeyguardUpdateMonitor_Factory.get(KeyguardUpdateMonitor_Factory.java:306)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
	at dagger.internal.DelegateFactory.get(DelegateFactory.java:4)
	at com.android.systemui.doze.DozeLog_Factory.get(DozeLog_Factory.java:2)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
	at com.android.systemui.statusbar.phone.DozeServiceHost_Factory.get(DozeServiceHost_Factory.java:4)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
	at com.android.systemui.keyguard.data.repository.KeyguardRepositoryImpl_Factory.get(KeyguardRepositoryImpl_Factory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
	at com.android.systemui.screenshot.RequestProcessor_Factory.get(RequestProcessor_Factory.java:82)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
	at com.android.systemui.keyguard.domain.interactor.KeyguardQuickAffordanceInteractor_Factory.get(KeyguardQuickAffordanceInteractor_Factory.java:2)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl.injectCustomizationProvider(DaggerReferenceGlobalRootComponent.java:2)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl.inject(DaggerReferenceGlobalRootComponent.java:4)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.systemui.SystemUIAppComponentFactoryBase$instantiateProviderCompat$1.onContextAvailable(SystemUIAppComponentFactoryBase.kt:42)
	at com.android.systemui.keyguard.CustomizationProvider.attachInfo(CustomizationProvider.kt:7)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7514)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7025)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6796)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by EleoXDA** [comment]
Did you even read Readme file? Please do

**Comment by Guarmanda** [comment]
I read it and saw that I use correct versions for each things, so I don't sée what do you mean by that?

**Comment by Guarmanda** [comment]
Oh ok, now it is only compatible with pixel phones? When i downloaded it it was compatible with every phone and thé project hadn't the same name. I auto updated it with magisk and it gave me this brand new thing that doesn't work with my mobile, weird

**Comment by Guarmanda** [comment]
I downgraded to 2.9, and now everything works with lineageos, sorry for inconvenience

**Comment by EleoXDA** [comment]
> Oh ok, now it is only compatible with pixel phones? When i downloaded it it was compatible with every phone and the project hadn't the same name. I auto updated it with magisk and it gave me this brand new thing that doesn't work with my mobile, weird

It was always only compatible with stock pixel firmware and no bugreport was ever accepted from any other custom/stock ROMs unless exactly same bugreport is provided from a stock pixel firmware. the difference is you are trying to use a mod that is made compatible with android 15 pixel stock firmware. and with any increment of fixes on stock pixel firmware there are chances of breaking custom ROM support - and thus, no custom ROM was ever supported in this MOD. Neither with old name, nor with new name (the reason of new name is basically to make it evidently clear that it is intended for stock pixel only, as AOSPMods was confusing to people and they were thinking it is compatible with custom AOSP as well)
